x-app-build: &app-build
  context: .
  dockerfile: Dockerfile
  args:
    TURBO_CONCURRENCY: ${TURBO_CONCURRENCY:-2}

services:
  db:
    image: postgres:17.6
    container_name: db
    env_file: .env
    ports:
      - "127.0.0.1:${POSTGRES_HOST_PORT}:5432"
    networks:
      - jungle-net
    volumes:
      - db:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

  migration:
    build:
      <<: *app-build
    command: ["node", "packages/database/dist/run-migrations.js"]
    networks:
      - jungle-net
    depends_on:
      db:
        condition: service_healthy
    env_file: .env

  payments:
    build:
      <<: *app-build
    container_name: payments
    command: ["node", "apps/payments/dist/src/main.js"]
    networks:
      - jungle-net
    depends_on:
      db:
        condition: service_healthy
      migration:
        condition: service_completed_successfully
      remnawave:
        condition: service_started
    env_file: .env
    ports:
      - "127.0.0.1:${PAYMENTS_PORT}:${PAYMENTS_PORT}"
    restart: always

  remnawave:
    build:
      <<: *app-build
    container_name: remnawave
    command: ["node", "apps/remnawave/dist/main.js"]
    networks:
      - jungle-net
    depends_on:
      migration:
        condition: service_completed_successfully
    env_file: .env
    ports:
      - "127.0.0.1:${REMNAWAVE_PORT}:${REMNAWAVE_PORT}"
    restart: always

  referrals:
    build:
      <<: *app-build
    container_name: referrals
    command: ["node", "apps/referrals/dist/main.js"]
    networks:
      - jungle-net
    depends_on:
      db:
        condition: service_healthy
      migration:
        condition: service_completed_successfully
      remnawave:
        condition: service_started
    env_file: .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB && psql -U $$POSTGRES_USER -d $$POSTGRES_DB -c 'SELECT 1' > /dev/null 2>&1" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "127.0.0.1:${REFERRALS_PORT}:${REFERRALS_PORT}"
    restart: always

  broadcasts:
    build:
      <<: *app-build
    container_name: broadcasts
    command: ["node", "apps/broadcasts/dist/main.js"]
    networks:
      - jungle-net
    depends_on:
      db:
        condition: service_healthy
      migration:
        condition: service_completed_successfully
    env_file: .env
    ports:
      - "127.0.0.1:${BROADCASTS_PORT}:${BROADCASTS_PORT}"
    restart: always

  webhook:
    build:
      <<: *app-build
    container_name: webhook
    command: ["node", "apps/webhook/dist/main.js"]
    networks:
      - jungle-net
    depends_on:
      db:
        condition: service_healthy
      migration:
        condition: service_completed_successfully
      payments:
        condition: service_started
    env_file: .env
    ports:
      - "127.0.0.1:${WEBHOOK_PORT}:${WEBHOOK_PORT}"
    restart: always

  web:
    build:
      <<: *app-build
    container_name: web
    command: ["apps/web/node_modules/.bin/serve", "apps/web/dist", "--single", "--listen", "tcp://0.0.0.0:${WEB_PORT:-7080}"]
    networks:
      - jungle-net
    ports:
      - "127.0.0.1:${WEB_PORT:-7080}:${WEB_PORT:-7080}"
    restart: always

  tma:
    build:
      <<: *app-build
    container_name: tma
    command: ["apps/tma/node_modules/.bin/serve", "apps/tma/dist", "--single", "--listen", "tcp://0.0.0.0:${TMA_PORT:-7090}"]
    networks:
      - jungle-net
    ports:
      - "127.0.0.1:${TMA_PORT:-7090}:${TMA_PORT:-7090}"
    restart: always

  bot:
    build:
      <<: *app-build
    container_name: bot
    command: ["node", "apps/bot/dist/main.js"]
    networks:
      - jungle-net
    depends_on:
      db:
        condition: service_healthy
      migration:
        condition: service_completed_successfully
      remnawave:
        condition: service_started
      payments:
        condition: service_started
      referrals:
        condition: service_started
      broadcasts:
        condition: service_started
    env_file: .env
    ports:
      - "127.0.0.1:${BOT_PORT:-7070}:${BOT_PORT:-7070}"
    restart: always


volumes:
  db:

networks:
  jungle-net:
    external: true