import type { TSubscriptionPageRawConfig } from '@remnawave/subscription-page-types';
import { env } from '@/config/env';

type TConfigsMap = Record<string, TSubscriptionPageRawConfig>;

/**
 * Fetches the subscription page config map from the static app-data.json.
 * In production this file is generated by the backend and served statically.
 */
export async function fetchAppConfig(): Promise<TConfigsMap> {
  const response = await fetch(`${env.appDataUrl}?v=${Date.now()}`);

  if (!response.ok) {
    throw new Error(`Failed to fetch app config: ${response.status}`);
  }

  return response.json();
}
